version: "2"
services:
  app:
    build: ./app
    links:
      - db
    ports:
      - "5000:5000"
  db:
    build: ./db
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root